### ISSUE TITLE
使用@arco-plugins/vite-vue@1.3.5 引入主题包 在vite^3.0.7不能运行在windows 浏览器（项目vite vue3 ts）

### ISSUE THREAD

**Issue by feng-0927** [arco-design/arco-plugins#38]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-webpack-plugin/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/webpack-plugin@1.7.0
- **框架版本:** vue ^3.2.37
- **浏览器版本:** chrome 107.0.5304.63

## 额外补充
报错：
下午5:43:45 [vite] Internal server error: path.replaceAll is not a function
  Plugin: @arco-plugins/vite-vue
  File: C:/fengzq/vue/practice/vite/vite-project/src/main.ts
      at parse2PosixPath (C:\fengzq\vue\practice\vite\vite-project\node_modules\@arco-plugins\vite-vue\lib\arco-design-plugin\utils.js:42:74)
      at pathMatch (C:\fengzq\vue\practice\vite\vite-project\node_modules\@arco-plugins\vite-vue\lib\arco-design-plugin\utils.js:48:51)
      at transformCssFile (C:\fengzq\vue\practice\vite\vite-project\node_modules\@arco-plugins\vite-vue\lib\arco-design-plugin\transform.js:34:47)        
      at TransformContext.transform (C:\fengzq\vue\practice\vite\vite-project\node_modules\@arco-plugins\vite-vue\lib\arco-design-plugin\index.js:46:58)  
      at Object.transform (file:///C:/fengzq/vue/practice/vite/vite-project/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:41111:44)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async loadAndTransform (file:///C:/fengzq/vue/practice/vite/vite-project/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:37373:29)

## 复现步骤
vite.config.ts中配置
import { vitePluginForArco } from '@arco-plugins/vite-vue'
  plugins: [
    vue(),
    AutoImport({
      resolvers: [ArcoResolver()],
    }),
    Components({
      resolvers: [
        ArcoResolver({
          sideEffect: true
        })
      ]
    }),
    vitePluginForArco({ theme: '@arco-themes/vue-byway' })
  ]
出现[vite] Internal server error: path.replaceAll is not a function

**Comment by feng-0927** [comment]
![62cc7d636f1c8c6b164b8164d1aac30](https://user-images.githubusercontent.com/52159058/197994537-143ae6d8-c768-463d-9947-9524e65faa81.jpg)

**Comment by feng-0927** [comment]
[project.zip](https://github.com/arco-design/arco-plugins/files/9868324/project.zip)

**Comment by jinghm318** [comment]
> ![62cc7d636f1c8c6b164b8164d1aac30](https://user-images.githubusercontent.com/52159058/197994537-143ae6d8-c768-463d-9947-9524e65faa81.jpg)

@feng-0927 我用你的包测试了下【node版本 16】，没有发现你说的问题，这个东西跟浏览器是无关的

**Comment by feng-0927** [comment]
已处理，是node版本问题，感谢
